name: CI Pipeline

# run-name: ${{ github.actor }} running the CI pipeline

permissions:
  contents: read

on:
  # run when pushing to main
  push:
    branches:
      - main
  # run on PRs based on main
  pull_request:
    branches:
      - main
  # also: allow to run this workflow manually
  workflow_dispatch:

jobs:
  check-format-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320
        name: Install pnpm
        with:
          cache: true

      - name: Install dependencies
        run: pnpm install --ignore-scripts

      - name: Check format
        run: pnpm run format

      - name: Lint
        run: pnpm run lint

  test-and-scan-with-sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320
        name: Install pnpm
        with:
          cache: true

      - name: Install dependencies
        run: pnpm install --ignore-scripts

      - name: Run tests with coverage report
        run: pnpm run test:coverage

      - name: Cache SonarQube packages
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@a31c9398be7ace6bbfaf30c0bd5d415f843d45e9
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # Check the Quality Gate status.
      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@cf038b0e0cdecfa9e56c198bbb7d21d751d62c3b
        with:
          pollingTimeoutSec: 600
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
